---
- assert:
    that:
      - exo_name is defined
    msg: >-
      Variable 'exo_name' should be defined to include this tasks file.

- name: Destroying Terraform (may take several minutes)
  shell: >
    terraform init &&
    terraform destroy -force
    -lock=false
    -var 'classroom_size={{ aws_padawans|length }}'
    -var 'key_name={{ key_name }}'
  args:
    chdir: "{{ playbook_dir }}/../terraform/{{ exo_name }}"
  register: tf_apply_raw
  changed_when: not (tf_apply_raw.stdout|search('0 added, 0 changed, 0 destroyed'))

- name: Enabling default inventory in ansible config
  lineinfile:
    dest: "{{ ansible_config_path }}"
    regexp: "{{ ansible_config_inventory_regexp }}"
    line: "{{ ansible_config_inventory_enabled }}"
    insertafter: "{{ ansible_config_insertion_regexp }}"

- name: Disabling ssh connection in ansible config
  blockinfile:
    dest: "{{ ansible_config_path }}"
    block: "{{ ansible_config_ssh_block }}"
    state: absent

- name: Removing generated files
  shell: >-
    rm {{ ssh_config_path }} {{ gen_inventory_path }}
  args:
    warn: no
  ignore_errors: yes
