---
# Gather facts about all hosts listed in inventory
- hosts: all

# Setting up bastion access
- hosts: bastion
  become: yes

  pre_tasks:
    - include_tasks: inc/bastion_pass.yml
      with_items: "{{ aws_padawans }}"
      loop_control:
        loop_var: bastion_pass_user
      tags: accesses

    - package:
        name: vim

  roles:
    - seed
    - prometheus-master
    - grafana
